local enum
enum = require("magick.enum").enum
local composite_operators = enum({
  [0] = "UndefinedCompositeOp",
  "AtopCompositeOp",
  "BlendCompositeOp",
  "BlurCompositeOp",
  "BumpmapCompositeOp",
  "ChangeMaskCompositeOp",
  "ClearCompositeOp",
  "ColorBurnCompositeOp",
  "ColorDodgeCompositeOp",
  "ColorizeCompositeOp",
  "CopyAlphaCompositeOp",
  "CopyBlackCompositeOp",
  "CopyBlueCompositeOp",
  "CopyCyanCompositeOp",
  "CopyGreenCompositeOp",
  "CopyCompositeOp",
  "CopyMagentaCompositeOp",
  "CopyRedCompositeOp",
  "CopyYellowCompositeOp",
  "DarkenCompositeOp",
  "DarkenIntensityCompositeOp",
  "DivideDstCompositeOp",
  "DivideSrcCompositeOp",
  "DstCompositeOp",
  "DifferenceCompositeOp",
  "DisplaceCompositeOp",
  "DissolveCompositeOp",
  "DistortCompositeOp",
  "DstAtopCompositeOp",
  "DstInCompositeOp",
  "DstOutCompositeOp",
  "DstOverCompositeOp",
  "ExclusionCompositeOp",
  "HardLightCompositeOp",
  "HardMixCompositeOp",
  "HueCompositeOp",
  "InCompositeOp",
  "IntensityCompositeOp",
  "LightenCompositeOp",
  "LightenIntensityCompositeOp",
  "LinearBurnCompositeOp",
  "LinearDodgeCompositeOp",
  "LinearLightCompositeOp",
  "LuminizeCompositeOp",
  "MathematicsCompositeOp",
  "MinusDstCompositeOp",
  "MinusSrcCompositeOp",
  "ModulateCompositeOp",
  "ModulusAddCompositeOp",
  "ModulusSubtractCompositeOp",
  "MultiplyCompositeOp",
  "NoCompositeOp",
  "OutCompositeOp",
  "OverlayCompositeOp",
  "OverCompositeOp",
  "PegtopLightCompositeOp",
  "PinLightCompositeOp",
  "PlusCompositeOp",
  "ReplaceCompositeOp",
  "SaturateCompositeOp",
  "ScreenCompositeOp",
  "SoftLightCompositeOp",
  "SrcCompositeOp",
  "SrcAtopCompositeOp",
  "SrcInCompositeOp",
  "SrcOutCompositeOp",
  "SrcOverCompositeOp",
  "VividLightCompositeOp",
  "XorCompositeOp",
  "DivideDstCompositeOp",
  "MinusDstCompositeOp",
  "ModulusSubtractCompositeOp",
  "ModulusAddCompositeOp",
  "ThresholdCompositeOp",
  "CopyAlphaCompositeOp"
})
local gravity = enum({
  [0] = "ForgetGravity",
  "NorthWestGravity",
  "NorthGravity",
  "NorthEastGravity",
  "WestGravity",
  "CenterGravity",
  "EastGravity",
  "SouthWestGravity",
  "SouthGravity",
  "SouthEastGravity",
  "StaticGravity"
})
local orientation = enum({
  [0] = "UndefinedOrientation",
  "TopLeftOrientation",
  "TopRightOrientation",
  "BottomRightOrientation",
  "BottomLeftOrientation",
  "LeftTopOrientation",
  "RightTopOrientation",
  "RightBottomOrientation",
  "LeftBottomOrientation"
})
local interlace = enum({
  [0] = "UndefinedInterlace",
  "NoInterlace",
  "LineInterlace",
  "PlaneInterlace",
  "PartitionInterlace",
  "GIFInterlace",
  "JPEGInterlace",
  "PNGInterlace"
})
-- added by yangx
local colorspace_types = enum({
  [0] = "UndefinedColorspace",
  "CMYColorspace",        
  "CMYKColorspace",      
  "GRAYColorspace",       
  "HCLColorspace",
  "HCLpColorspace",
  "HSBColorspace",
  "HSIColorspace",
  "HSLColorspace",
  "HSVColorspace",          
  "HWBColorspace",
  "LabColorspace",
  "LCHColorspace",          
  "LCHabColorspace",         
  "LCHuvColorspace",         
  "LogColorspace",
  "LMSColorspace",
  "LuvColorspace",
  "OHTAColorspace",
  "Rec601YCbCrColorspace",
  "Rec709YCbCrColorspace",
  "RGBColorspace",           
  "scRGBColorspace",        
  "sRGBColorspace",          
  "TransparentColorspace",
  "xyYColorspace",
  "XYZColorspace",          
  "YCbCrColorspace",
  "YCCColorspace",
  "YDbDrColorspace",
  "YIQColorspace",
  "YPbPrColorspace",
  "YUVColorspace"
})
return {
  composite_operators = composite_operators,
  gravity = gravity,
  orientation = orientation,
  interlace = interlace,
  colorspace_types = colorspace_types
}
